### ISSUE TITLE
plugdata regressions

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#1192]
Here are some issues that I noticed in the latest source. Tested on Arch (Manjaro, actually), running Pipewire and Jack2 as the audio server. The issues are the same with both the current develop branch and the 0.8.0-test pre-release.

- In the stand-alone, MIDI output to the internal gmsynth doesn't appear to work (no sound). Output to external qsynth/fluidsynth works ok.

- MIDI output in the VST3 plugin doesn't work, at least not in Ardour. LV2 works ok.

- Also, where did the new MIDI port system go (see, e.g., #1009)? I see that the code in Source/Dialogs/MIDISettingsPanel.h and Source/Utility/MidiDeviceManager.h is still there, but note output always goes to all connected MIDI devices again (whereas MIDI input seems to distinguish different input ports by channel number), and the run-mode device menu on MIDI objects has also disappeared. Did you revert that for some reason?

**Comment by timothyschoen** [comment]
Thanks, I'll get these sorted out before the final release!

As for the MIDI port system, I decided it was a bit annoying to have a single MIDI output selected as the default when creating a MIDI object. So, I decided to do something similar to what Max does, send it to all MIDI devices by default, but still offer the option to select a single device if you wish:

<img width="214" alt="Screenshot 2023-09-22 at 13 05 13" src="https://github.com/plugdata-team/plugdata/assets/44585538/a3d46c81-6f43-4b47-9451-14f1b5b90de0">

The device menu hasn't disappeared, but we needed to make an adjustment to it. People requested the option to have a right-click menu in locked mode, since you can do that in pd-vanilla too. So now, you need to double-click on the MIDI object to select the device. This is also how Max handles it, so to some users it should be familiar, but I do want to think about ways to make this more discoverable in the future.

**Comment by timothyschoen** [comment]
Ah, the problem was that the GM synth didn't receive MIDI when you select "All devices". Should be fixed!

**Comment by timothyschoen** [comment]
<img width="998" alt="Screenshot 2023-09-22 at 14 01 56" src="https://github.com/plugdata-team/plugdata/assets/44585538/0b30feed-880b-464e-90c8-ff21acf0a519">

I am getting MIDI from the VST3 plugin, I'll try it in Ardour now. Do you know if this worked before?

**Comment by agraef** [comment]
> Ah, the problem was that the GM synth didn't receive MIDI when you select "All devices". Should be fixed!

Yep, works now.

> So now, you need to double-click on the MIDI object to select the device. This is also how Max handles it, so to some users it should be familiar, but I do want to think about ways to make this more discoverable in the future.

Ok, I understand. Nice. But yeah, it's kind of hard to discover this if you don't know Max. If this isn't too much hassle, maybe the device options could also be added as a submenu to the context menu?

> I am getting MIDI from the VST3 plugin, I'll try it in Ardour now. Do you know if this worked before?

Yes, it did. I still have a few sample Ardour sessions where I did use the VST3 plugdata-fx rather than the LV2 because of the parameter name editing capabilities, and they all stopped working.

**Comment by timothyschoen** [comment]
I'm able to reproduce the MIDI issue: in REAPER on macOS, it behaves similarly. The LV2 fx plugin can send MIDI out, but the VST3 or AU fx plugin can't.

**Comment by timothyschoen** [comment]
Okay, it took me a second to find out how MIDI works in Ardour, but it looks like I'm now able to send MIDI out from Ardour on Linux, both from the VST3 and LV2 fx plugins:

![Screenshot from 2023-09-27 23-37-11](https://github.com/plugdata-team/plugdata/assets/44585538/fff1ba9f-2d47-48de-a035-29a302882459)

Is it possible that updating plugdata may have messed up Ardour's pin connections?


![Screenshot from 2023-09-27 23-39-14](https://github.com/plugdata-team/plugdata/assets/44585538/9e623b35-07dd-4078-b46f-1787b505a724)

**Comment by timothyschoen** [comment]
I did fix a bug with [midiout] that was introduced recently, maybe that was the problem?

**Comment by timothyschoen** [comment]
> No dice, I just built the latest from git, it's still the same, neither MIDI input nor output is working with the vst, whereas both work fine with the lv2. Pin connections look alright. (I have the plugin pre-fader, as it should be, though. But I also tried it post-fader, doesn't make a difference.)
> 
> One interesting thing I noticed if I have the vst pre-fader, it just seems to pipe the incoming MIDI through as if the MIDI input/output was "bridged" somehow, if that makes any sense.
> 
> Tried 0.7.1, there the MIDI in the vst works fine. And it also still works with rev. [fb58ebe](https://github.com/plugdata-team/plugdata/commit/fb58ebeff1c42771505873af547c47b01ffa9290), which was one of the revisions I played around with in August. So this _must_ be a recent regression. Maybe a recent upgrade of the VST3 SDK tripped this bug? (Just a wild guess.) Other than that, if you don't have an idea what might be causing this issue, I'm afraid that it's bisection time again. :(

I'm afraid so too... I was hoping I could reproduce it, but no luck. I was using Ardour 7.5.0 on Fedora (arm64).

I'm also completely clueless about where this is coming from, AFAIK I only touched MIDI handling for the standalone, I don't remember changing anything for the plugins, but I guess I must have done something wrong.

**Comment by timothyschoen** [comment]
If you'd have time to do a bisection, that would help. I'm ready to release v0.8.0, just waiting to see if this bug can get fixed.

No pressure though, If you don't have time, it's also fine with me to leave this for v0.8.1. It doesn't seem affect every version of Ardour (apparently), and the LV2 does work.

**Comment by agraef** [comment]
Hi Tim, sorry, I didn't have the time to look into this yet, and with the semester starting next week, I doubt that I can devote any time on this for the time being.

Yes, MIDI I/O works with the LV2, but there I can't change any of the param names. :( So I guess I'll just have to wait until the present issue gets fixed.

**Comment by timothyschoen** [comment]
> Hi Tim, sorry, I didn't have the time to look into this yet, and with the semester starting next week, I doubt that I can devote any time on this for the time being.
> 
> Yes, MIDI I/O works with the LV2, but there I can't change any of the param names. :( So I guess I'll just have to wait until the present issue gets fixed.

No problem!

Yeah, it should still get fixed at some point. I just updated to JUCE v7.0.8 (the regressions we had before have been fixed), perhaps it helps.

**Comment by agraef** [comment]
FWIW, I just downloaded the latest Arch build and the VST3 still doesn't do MIDI.

BTW, building the latest from develop on Manjaro myself, I'm suddenly getting this compile error:

~~~
[  3%] Building C object Libraries/CMakeFiles/fluidlite.dir/FluidLite/src/fluid_init.c.o
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
~~~

This is with gcc (GCC) 13.2.1 20230801 which seems to be the latest from Arch. Oddly enough, I don't see that error in the build logs on GH, the module compiles fine there, so maybe it's a local issue.

**Comment by agraef** [comment]
The VST works fine in Carla, though, so this really seems to be an issue with Ardour. It looks like it gets confused with the routing. Maybe this is a regression in Ardour 8 (I can't test that right now, since the older 7.x version isn't in the Arch repositories any more, it's been superseded by 8.0).

So it seems that everything is fine with the VST in plugdata 0.8 after all. I'll close this bug and report it with Ardour as soon as I find the time. I'll also play around with Ardour's routing options and see whether I can work around this issue.

**Comment by agraef** [comment]
I guess I can also make do with the LV2 and be content with the generic parameter names for now, or shun the automation parameters in favor of MIDI automation.

Anyway, thanks a bunch for your time and patience, and special thanks for putting out a release, just in time for the new semester! ;-) A big shoutout to the entire team, 0.8.0 is looking really good!

**Comment by timothyschoen** [comment]
> I guess I can also make do with the LV2 and be content with the generic parameter names for now, or shun the automation parameters in favor of MIDI automation.
> 
> Anyway, thanks a bunch for your time and patience, and special thanks for putting out a release, just in time for the new semester! ;-) A big shoutout to the entire team, 0.8.0 is looking really good!

Thanks! It was definitely the most stable version so far. Good luck next semester!

I guess your compiler might be too new? I'll just remove that flag. The next version is shaping up nicely but you might want to stay away a little longer if you want something stable ;)

**Comment by agraef** [comment]
I think I'll have to reopen this, because I have the same issues on the Mac, with neither VST nor AU giving me any MIDI output in Ardour. Only the LV2 works there.

Since this all worked fine before in plugdata 0.7.1, this *must* be a regression in plugdata which should be looked into some time.

**Comment by agraef** [comment]
One thing that I forgot to mention earlier is that the metronome (metro object) isn't working either in the VST. (In the AU that does work, it's only the MIDI output that's missing.) I also noticed this on Linux, so things go really wrong with the VST in Ardour. Can anyone please try to reproduce these issues? I can't believe that I'm the only one who sees this. It's 100% reproducible for me.

**Comment by agraef** [comment]
I've attached a very basic test example:

[bug.pd.zip](https://github.com/plugdata-team/plugdata/files/13222508/bug.pd.zip)

Create a new Ardour session, add a MIDI track with a synth (or the ACE MIDI Monitor), insert plugdata-fx (AU or VST) at the front of the signal chain, load bug.pd and engage the toggle which starts note output.

There's no MIDI output whatsoever, and with the VST the metro only produces a single bang and then dies (as can be seen in the bang gui). It looks like the realtime thread in the VST just dies or hangs, whereas in the AU the engine keeps running fine, it just doesn't produce any MIDI output. With the LV2, everything works fine.

As I said, this is new in plugdata 0.8.0, the VST worked just fine with earlier versions.

**Comment by agraef** [comment]
One more data point: After renewing my Bitwig license, I was able to test the plugdata-fx VST there. The VST works fine in Bitwig on Linux, i.e. MIDI output from the VST gets transmitted properly to next synth plugin in the signal chain, all good.

Maybe there were some breaking changes in VST3 (or the way JUCE utilizes it) recently which just throws off Ardour's VST interface? And might there be a similar issue which affects the AU in Ardour on Mac? That's the only explanation I have, because if there was an issue somewhere else in the plugdata MIDI code, that would surely show in Bitwig as well, wouldn't it?

**Comment by timothyschoen** [comment]
> One more data point: After renewing my Bitwig license, I was able to test the plugdata-fx VST there. The VST works fine in Bitwig on Linux, i.e. MIDI output from the VST gets transmitted properly to next synth plugin in the signal chain, all good.
> 
> Maybe there were some breaking changes in VST3 (or the way JUCE utilizes it) recently which just throws off Ardour's VST interface? And might there be a similar issue which affects the AU in Ardour on Mac? That's the only explanation I have, because if there was an issue somewhere else in the plugdata MIDI code, that would surely show in Bitwig as well, wouldn't it?

I'm not completely sure, but I think plugdata v0.7.1 and v0.8.0 use the same JUCE version, so if that's true, it has to be something in plugdata itself. I'll also take a look at the patch you sent tomorrow.

**Comment by agraef** [comment]
Ok, I did another round of tests now on both Arch and macOS, using only the official downloads for the 0.7.1 and 0.8.0 versions from https://github.com/plugdata-team/plugdata/releases. The results confirm what I reported earlier:

The VST from 0.7.1 works in Ardour, the 0.8.0 version doesn't (metro dies after first tick, and there's no MIDI output whatsoever). It's exactly the same behavior on both Linux (Intel PC running the latest Manjaro) and Mac (MB M1 Air running the latest Ventura version). On the Mac, the AU doesn't produce MIDI output with *either* version, so it seems to be a different bug with the AU.

I used the latest Ardour version (8.1). Here's the Ardour session that I used for testing. (This just has a single MIDI track with the plugdata-fx VST running the bug.pd from above, an ACE MIDI Monitor, and the Reasonable synth on it, which should run on any Ardour installation, provided that you have plugdata installed. I had to zip up the session archive since GH won't let me upload that file type as is, so you need to unzip it first.)

[plugdata-bug.ardour-session-archive.zip](https://github.com/plugdata-team/plugdata/files/13254169/plugdata-bug.ardour-session-archive.zip)

**Comment by agraef** [comment]
> One more data point: After renewing my Bitwig license, I was able to test the plugdata-fx VST there. The VST works fine in Bitwig on Linux, i.e. MIDI output from the VST gets transmitted properly to next synth plugin in the signal chain, all good.

Well actually, I've had the 0.8.0 VST plugin crashing there as well. So it's not all good in Bitwig either. Bitwig just seems to be better than Ardour in detecting misbehaving plugins.

**Comment by timothyschoen** [comment]
> Ok, I did another round of tests now on both Arch and macOS, using only the official downloads for the 0.7.1 and 0.8.0 versions from https://github.com/plugdata-team/plugdata/releases. The results confirm what I reported earlier:
> 
> The VST from 0.7.1 works in Ardour, the 0.8.0 version doesn't (metro dies after first tick, and there's no MIDI output whatsoever). The LV2 works fine in both 0.7.1 and 0.8.0. It's exactly the same behavior on both Linux (Intel PC running the latest Manjaro) and Mac (MB M1 Air running the latest Ventura version). On the Mac, the AU doesn't produce MIDI output with _either_ version, so it seems to be a different bug with the AU.
> 
> I used the latest Ardour version (8.1). Here's the Ardour session that I used for testing. (This just has a single MIDI track with the plugdata-fx VST running the bug.pd from above, an ACE MIDI Monitor, and the Reasonable synth on it, which should run on any Ardour installation, provided that you have plugdata installed. I had to zip up the session archive since GH won't let me upload that file type as is, so you need to unzip it first.)
> 
> [plugdata-bug.ardour-session-archive.zip](https://github.com/plugdata-team/plugdata/files/13254169/plugdata-bug.ardour-session-archive.zip)

Seems like there is definitely some kind of deeper issue there. Not sure if the broken scheduling (metro, etc.) and lack of MIDI output are related, but both need to be fixed.

I looked at all the acceptsMidi/producesMidi flags in PluginProcessor.cpp and the NEEDS_MIDI_INPUT/NEEDS_MIDI_OUTPUT flags in cmakelists. Looks like those are set correctly, and they haven't changed in a long time. So there has to be something else that is impacting this. But it's still a mystery to me what that could be.

But what's even more strange, is that I still can't reproduce this on macOS (Sonoma, M1 MBP) following the steps your described above exactly. I'm using the plugdata v0.8.0 VST3 inside Ardour 8.1.0. The metro issue and MIDI issue both don't happen here. I wish it would, so I could actually fix it. It's really baffling since we are also using nearly the same setup.

https://github.com/plugdata-team/plugdata/assets/44585538/204030f3-319c-434c-9b13-4429b92fcd3c

**Comment by timothyschoen** [comment]
If [metro] stops working but clicking on a bang still works, that is usually a sign that the DAW is not sending audio blocks in, which will then mean that Pd's scheduling won't run (since it runs on the audio thread). That seems like the most likely explanation of that issue for me.

**Comment by agraef** [comment]
Your session is *not* the same as mine, you have the synth before the plugin. Indeed, if I modify my session that way then I *am* getting MIDI output. But that's not the proper order of plugins; the synth needs to come after the plugin so that I can hear the MIDI output. Try moving the synth after plugdata, where it belongs. Then you should be able to reproduce the problem that I'm having.

> If [metro] stops working but clicking on a bang still works, that is usually a sign that the DAW is not sending audio blocks in, which will then mean that Pd's scheduling won't run (since it runs on the audio thread).

Ok, that explains it. But that makes it impossible to use plugdata-fx as a MIDI effect on a MIDI track. If you place plugdata-fx on the beginning of a MIDI track, there *is* no audio coming into it, no matter what.

Note that plugdata 0.7.1 behaves differently, it *does* work as a MIDI plugin and runs fine without any audio input. As does the LV2 in both plugdata versions. And that's how it's supposed to work IMHO.

**Comment by timothyschoen** [comment]
So that was the difference! I can reproduce it now, so I'll start debugging this. I misunderstood this part from the beginning. I'm now 90% sure that this is the problem:

<img width="596" alt="Screenshot 2023-11-05 at 17 44 43" src="https://github.com/plugdata-team/plugdata/assets/44585538/af71059a-6050-472c-96f2-13efb52e0321">

It was necessary to fix a bug, but looks like we'll need to solve that bug differently so that we don't break this.

**Comment by agraef** [comment]
Actually, I think that the processing callback should be called in any case, even if there is no actual audio input, otherwise the 0.7.1 version of plugdata-fx vst wouldn't work either. In fact, none of Ardour's other MIDI vst3 plugins would then work (of which there are plenty), and they certainly do. Maybe there was a recent change in the callback of plugdata, or some related change that causes this behavior?

In any case, I consider this a bug which must be fixed. But at least I know how to work around this issue for now. I just need to enable the audio sidechain in the pin connections of plugdata-fx, then it will work even at the beginning of the signal chain (and even if there is no actual audio connected to the sidechain audio ports).

Ok, it seems that we drilled down to the root cause of the issue at least. Any idea how to fix it? :)

**Comment by agraef** [comment]
Sorry, our messages crossed. Yeah, that's definitely the issue there. Glad that you found it, it can't be too hard to fix it now.

**Comment by timothyschoen** [comment]
The line was apparently needed to fix some assertions, as the commit message reads "Fixed assertion failures when the block size or number of channels equals 0". So I can just remove this line for now, since the issue you described is more severe than the assertions. After that I can look into a better way to get rid of the assertions.

**Comment by agraef** [comment]
Better look at the assertions then. That sounds like you might be accessing some audio buffer pointer further down in the callback that's not guaranteed to point to anything, a sure recipe for odd crashes. ;-)

**Comment by timothyschoen** [comment]
16894d6eea6a5e8b9867c7d1541d22f651ebb3f5 should fix it!

So far, I didn't hit any assertions during the processBlock function, in standalone or plugin. So I'll just see if they pop up again. I remember that it was just JUCE being pedantic, it would complain if one of the DSP components would get called with 0 channels, even though it handles it correctly.

**Comment by agraef** [comment]
Currently building, will test.

**Comment by agraef** [comment]
I'm still getting this error when trying to build plugdata myself on Manjaro:

~~~
[  3%] Building C object Libraries/CMakeFiles/fluidlite.dir/FluidLite/src/fluid_init.c.o
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
~~~

Probably some funkyness in printf usage in the FluidLite code is causing this, or maybe the cmake config is borked in some way. The problem is that I can't seem to get rid of this stupid (non-)error, no matter what I add to the cmake command line when configuring plugdata. Can anyone help?

**Comment by agraef** [comment]
Using the latest build from https://github.com/plugdata-team/plugdata/actions/runs/6762865286 I can confirm that the VST works on Arch now. Hurray! :) I will test on the Mac tomorrow.

I'd still like to be able to build this myself, so I should submit the compilation problem I have as a separate issue.

**Comment by agraef** [comment]
VST works on Mac now, too, nice! :)

But MIDI output from the AU is still broken, this seems to be a separate issue. So I'm leaving this ticket open for now.

**Comment by timothyschoen** [comment]
I'm not sure if MIDI output from AU instrument and fx is possible with JUCE. There is a AU MIDI effect version of plugdata, which you can use in Logic to process MIDI.

**Comment by agraef** [comment]
> There is an AU MIDI effect version of plugdat

Ah yes, I see. So I guess that we can close this issue then.
