### ISSUE TITLE
[keyboard] color remains when using with [metro]

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1234]
hello. sorry for the issues before. for the coloring issue for `keyboard`, it worked well when I updated to the newest version (v.0.8.0.)

but I just encountered with another problem. when I send bang messages manually, the keys are colored without any problems. but when I tried to send bang automatically through `metro`, and set the velocity (probably) longer than 492, the triggered colors are remaining on the `keyboard` GUI. which is not happening in pd-vanilla. is it still a bug or am I doing wrong something? my current plug is v.0.8.0, ELSE v1.0-rc9. thanks in advance.

======================

[when trying with `metro`]

https://github.com/plugdata-team/plugdata/assets/68152553/d453e964-6164-44e8-bc8a-9d3d9b5440b0

[when trying with `random`]

https://github.com/plugdata-team/plugdata/assets/68152553/6861869d-712e-48b3-9a94-4a29f7543a59

[when adjusting velocity]

https://github.com/plugdata-team/plugdata/assets/68152553/d467b4a3-d101-4825-a2d2-2f0fcaceaf3b

[when trying on vanilla]

https://github.com/plugdata-team/plugdata/assets/68152553/1e32d8fe-03a0-4892-bf8a-a367d852008d

**Comment by timothyschoen** [comment]
Thanks for reporting!

I'm not sure what caused this issue, but on the latest nightly build, I can't reproduce it anymore, so I hope it is now fixed?

https://github.com/plugdata-team/plugdata/assets/44585538/88c2919f-d232-4995-a99e-e4f7f105c2ae

**Comment by H-MLim** [comment]
yes it worked on 0.8.1! (it seems sometimes it didn't work but I'm not sure...but most of case, it worked well.)
there are few problems still, for example still the colors are remaining under the faster tempo (probably under than `metro` 102), but since such a fast tempo is not important for my patches, it's not a big issue for now. but I hope there would be any possibilities to be fixed in the future. anyway it's still better than before. thanks a lot!

**Comment by H-MLim** [comment]
(btw it appears again in recent (un)stable builds.)

**Comment by timothyschoen** [comment]
I think this is really fixed now with c86297943bd5cbfa1ab6595e6a2df51004d36010!

**Comment by H-MLim** [comment]
ah. yes. it seems it is fixed. thanks!
