### ISSUE TITLE
hslider/vslider visually resets to zero on dropping a new object from the selection pane

### ISSUE THREAD

**Issue by muziker** [plugdata-team/plugdata#1509]
Plugdata 0.8.3 built from github v0.8.0-766.

When drag and dropping an object from the object selection pane, the hslider/vslider resets visually to zero. I'm not sure if this is intended behaviour but that's what it does.

Really nice graphics btw.

**Comment by muziker** [comment]
In ubuntu 20.04

**Comment by dromer** [comment]
Also happens when you save a patch.

**Comment by muziker** [comment]
Tried this on the develop branch, and that branch seems to work fine.

**Comment by timothyschoen** [comment]
I think this is fixed then?

**Comment by dromer** [comment]
It no longer fully resets, but I still see it jump down a tiny bit.
It's only visual though, its output does not change.
