### ISSUE TITLE
Internal GM Synth outputs weird noises

### ISSUE THREAD

**Issue by H-MLim** [plugdata-team/plugdata#1577]
https://github.com/plugdata-team/plugdata/assets/68152553/46c471b4-b016-46ff-a6c1-e7316012adad

hi. when outputs the sound with like `[keyboard]`-`[makenote]`, it should sound the ordinary Piano sound with Internal GM Synth. instead it outputs weird disturbing noise. how should I fix this? on the other hand, Microsoft GS Wavetable Synth outputs the Piano sounds normally. it tested with Win 11 - Nightly build: d5498b418

**Comment by timothyschoen** [comment]
Should be fixed!

**Comment by H-MLim** [comment]
thank you for checking! but I'm afraid the issue is still continuing in the current build (Nightly build: 47773d37a). can you reproduce it still?

**Comment by H-MLim** [comment]
I found something interesting. I tried to replace with some other sf3. soundfont files. but every soundfont outputs very disturbing noises as I reported before. I think the connection between soundfont file and plugdata could be a problem.

**Comment by H-MLim** [comment]
seems to be fixed!

**Comment by H-MLim** [comment]
hi, seems it happens again in Nightly build: 885a64577. could you reproduce it? I'm using Windows 11, and mme sound driver (Realtek High Definition Audio)
