### ISSUE TITLE
Compressed font rendering on Fedora 40

### ISSUE THREAD

**Issue by yioannides** [plugdata-team/plugdata#1673]
Hello again, I wanted to also bring up the subject of font rendering on Linux. I've seen that the font rendering is impeccable on macOS, but in a lot of Linux distros, the font rendering is rather aliased and compressed, as seen below:

![Screenshot from 2024-06-25 20-34-21](https://github.com/plugdata-team/plugdata/assets/154235768/8e68bc49-b38a-42b5-9170-5c0daf4e9946)

Not sure if this is a Wayland issue or a plugdata issue, but I thought it would be worth mentioning. Thank you.

**Comment by alcomposer** [comment]
Having worked on this with Tim my understanding is it's a JUCE issue. 

For macOS/Windows fonts are subpixel. But Linux doesn't get that ability.

Not much we can do about that I'm afraid. I have also noticed this issue on Linux myself, so it is a rel issue with JUCE issues on their GH.

**Comment by yioannides** [comment]
Thank you for responding! Is it worth creating an issue on JUCE's GH or is there an existing one / has already been addressed?

I'd imagine the option below is not relevant to this issue, right?

![image](https://github.com/plugdata-team/plugdata/assets/154235768/53754514-4012-4061-b33a-e9da9bd917f0)

**Comment by alcomposer** [comment]
JUCE font rendering is a known pain point in JUCE Linux, going back years.

JUCE Linux is getting better however, but it may take more time for the devs to get around to fixing font rendering engine issues.

**Comment by timothyschoen** [comment]
I think this is actually something they have addressed with JUCE 8. However, I'm sticking to JUCE 7 for a bit longer because JUCE 8 is just out, and might still be a bit rough around the edges. But I think this will be improved in the future!

It bothers me too that the icons in toolbar render less good on Linux, since that's also done with font rendering :(

**Comment by yioannides** [comment]
I see JUCE v8 is 2 weeks old, so yeah I understand... plugdata is a wonderful piece of software, that's why it makes me sad that the rendering is still not up to par with macOS/Windows, but I'm sure it'll all work out in the end!

**Comment by alcomposer** [comment]
@timothyschoen I am going to close this issue, as it is mainly a bug in JUCE. We hope we can fix this soon, and that JUCE V8 does actually fix this. :-D

**Comment by timothyschoen** [comment]
The develop branch now uses JUCE 8, which should make text look a lot better on Linux!
