### ISSUE TITLE
Clicking on the objects on the `openfile` object help document crashes with an address boundary error

### ISSUE THREAD

**Issue by bauhaushousedog** [plugdata-team/plugdata#1919]
Both stable and nightly crashes.

steps to reproduce:
1. open plugdata
2. create `openfile` object
3. go on the help document
4. click on any object
5. crash

https://github.com/user-attachments/assets/eb7844f2-445d-4951-8d0e-771de1ad043f

my system info:
![image](https://github.com/user-attachments/assets/ebf79a63-b4aa-4a84-a16c-6197cd8dda31)

**Comment by bauhaushousedog** [comment]
although i have used plugdata for a few hours basic functionality does work

**Comment by bauhaushousedog** [comment]
extra info: tried it out in a different host (lmms + carla and plugdata as vst) and the host and everything else crashed and closed

**Comment by timothyschoen** [comment]
I was able to reproduce it! Should now be fixed with 4ff4d62b4

**Comment by bauhaushousedog** [comment]
> I was able to reproduce it! Should now be fixed with [4ff4d62](https://github.com/plugdata-team/plugdata/commit/4ff4d62b4ef8d2bf5ade89095f2be78283a8bf8f)

thanks for the quick fix! going to test it on the latest nightly

**Comment by bauhaushousedog** [comment]
problem still persists, is there a way to get a stacktrace/verbose terminal output on plugdata?

https://github.com/user-attachments/assets/fc69e804-b9c8-4691-ab29-4b428433fe45
