### ISSUE TITLE
Raspbian 12: could not initialise nvg

### ISSUE THREAD

**Issue by alexmlucas** [plugdata-team/plugdata#2100]
I installed Plugdata 0.9.1 on Raspbian 12 via the binary package. When I run Plugdata the canvas is black and I cannot see any objects I create. 

In the terminal window I see the following message 

```
could not initialise nvg
Shader shader/vert error:
``` 

When I quit Plugdata I get the following additional message in the terminal.

`JUCE Assertion failure in juce_OpenGLContext.cpp:690`

Any help would be very much appreciated!

![Image](https://github.com/user-attachments/assets/1dc2f918-5088-46e2-937e-3621c7c97a8a)

**Comment by alexmlucas** [comment]
This was a RPi 500, but I also encountered the same problem on a RPi 5 also running Raspbian 12. Seemingly these models support OpenGL ES 3.0 and 3.1 respectively. I was reading that ES is an acronym for Embedded Systems. According to Wikipedia this is a subset of OpenGL. Could that be an issue?

**Comment by dromer** [comment]
Afaik plugdata should be able to run on those!

I don't have one myself to help test, but I assume you maybe need to install some additional tools to make it work.

**Comment by carthach** [comment]
v0.9.2 will have Raspberry PI working again I believe...

**Comment by daveclavsell** [comment]
I have the same issu with my CM4 module on v0.9.1

**Comment by headstrongsolutions** [comment]
> v0.9.2 will have Raspberry PI working again I believe...

Is there any detail on when the repos will be updated to v0.9.2 for all of the distro's package managers?

**Comment by dromer** [comment]
@headstrongsolutions v0.9.2 is not released yet. There is no set date of when this will happen.

**Comment by timothyschoen** [comment]
This is now fixed!

If you build from source, you'll need to add the `-DNANOVG_GLES_IMPLEMENTATION=1` flag to cmake.

Or, you can download the "Debian (aarch64)" build from here: https://plugdata.org/download.html, at the bottom of the page. This has been confirmed to work on Rpi too!

**Comment by alexmlucas** [comment]
Unfortunately this is still and issue for me both with 0.9.2 via the "Add repository and install manually option" and the latest Debian (aarch64) build 11b5050

**Comment by alexmlucas** [comment]
Thanks for your response. I've now tested both X11 and Wayland. Unfortunately the issue persists with both.

**Comment by alexmlucas** [comment]
I've now managed to resolve the issue! I'm using Raspberry Pi OS 13 Trixie on a Raspberry Pi 5. 
To get this to work on my machine, I switched to X11 via raspi-conifg. I then run plugdata from the terminal using the following command  

`LIBGL_ALWAYS_SOFTWARE=1 plugdata`
