### ISSUE TITLE
menu_openfile support

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#303]
I'm not sure whether it is possible in plugdata, but it would be nice if vanilla's menu_openfile protocol could be implemented.

This is a Tcl routine named `::pd_menucommands::menu_openfile` called via sys_vgui. It takes one argument, the name of the file to be opened, which can be a Pd patch to be opened in Pd, but also a text file or really any file that the host OS knows how to deal with. This is used, e.g., in pd-lua to open the Lua source for a Lua object, which is convenient. It is also being used in various other externals.

I'm not sure whether this is properly documented anywhere, but the Tcl command can be found in
[pd_menucommands.tcl](https://github.com/pure-data/pure-data/blob/master/tcl/pd_menucommands.tcl), (at line 292 at the time of this writing).

Similar (though unrelated): It would be nice to have the possibility to open non-patch files, like text files, html, or pdf, from the documentation browser.

**Comment by timothyschoen** [comment]
Should be possible to implement that, I already have some hooks inside sys_vgui. The thing I'm wondering about is when this protocol is used, so I can test to see if it works.

The behaviour for non-patch files in the document browser is that it puts the path inside a message. I thought this would be a nice way to quickly access paths of audio files you use often. Maybe another implementation would be better.

**Comment by timothyschoen** [comment]
Ah I see, [pdcontrol] uses it!

**Comment by timothyschoen** [comment]
It should work now!

**Comment by agraef** [comment]
Right, opening a text file with [browse /etc/passwd( - [pdcontrol] actually works now, thanks. (Not the webpage example from the pdcontrol-help patch, though.)

But Open in the context menu still isn't working, so it seems that there's still some callback missing in plugdata. What I mean are objects with a definition for the menu-open method, like in pd-lua (excerpt from the pd-lua source):

~~~c
/* a class with a "menu-open" method will have the "Open" item highlighted in the right-click menu */
    class_addmethod(c, (t_method)pdlua_menu_open, gensym("menu-open"), A_NULL);/* (mrpeach 20111025) */
~~~

Sorry, I don't think that there's a minimal example for this. But g_canvas.c has this method, too. So this might be related to another defect I noticed, namely that I can't open gop abstractions with Open in plugdata either; the option is just always greyed out in the context menu. In vanilla this works -- right-click on a gop subpatch, choose Open from the menu, and the subpatch opens. What *does* work in plugdata is opening non-gop subpatches; both the Open option is available, and I can also open the subpatch by just clicking on it, like in vanilla.

So if you can fix the issue with the canvas menu-open not working properly, I have hopes that opening Lua source files from pdlua objects will magically start working as well. :)

**Comment by agraef** [comment]
Just tried, and at least in 0.53.1, sys_vgui still seems to work fine. pd-lua still uses that. Looks like it's deprecated in favor of pdgui_vmess, though. No problem, I can update pd-lua accordingly. 

Seems like pdgui_vmess is a more language-neutral interface, akin to what we have in Purr Data. Maybe to open Pd up to alternative GUI toolkits? Just a wild guess...

**Comment by timothyschoen** [comment]
Calling it with sys_vgui still works, but internally Pd no longer uses that, so I have to support both.


> Seems like pdgui_vmess is a more language-neutral interface, akin to what we have in Purr Data. Maybe to open Pd up to alternative GUI toolkits? Just a wild guess...

That is the intention I believe, I'm not sure if it will be very useful for plugdata.

**Comment by agraef** [comment]
Ok, I can hopefully take a look next week.

**Comment by timothyschoen** [comment]
I think I'll take a look at it tonight. My current plan is to release the next version on Sunday. I'm going to spend most of tomorrow and Saturday on testing. There's already so many new features and important bugfixes in this version that I shouldn't hold it off much longer.

**Comment by timothyschoen** [comment]
This should be fixed now, could you confirm that?

**Comment by agraef** [comment]
I'm running rev. 156cd3e6df0c275127cb6e3cd053ae07b114014c here which I downloaded last night, but should have everything before you merged #327. It still has the issue (Open grayed out, both with pdlua and gop abstractions/one-offs).

**Comment by agraef** [comment]
Well, I can tell you where this is in the vanilla source, have a look at g_editor.c:1799 (the definition of canopen is what's relevant here):

~~~c
    /* right-clicking on a canvas object pops up a menu. */
static void canvas_rightclick(t_canvas *x, int xpos, int ypos, t_gobj *y)
{
    int canprop, canopen;
    canprop = (!y || class_getpropertiesfn(pd_class(&y->g_pd)));
    canopen = (y && zgetfn(&y->g_pd, gensym("menu-open")));
    pdgui_vmess("pdtk_canvas_popup", "^ ii ii",
        x,
        xpos, ypos,
        canprop, canopen);
}
~~~

**Comment by agraef** [comment]
And here's a little test example: [open-test.zip](https://github.com/plugdata-team/plugdata/files/10360028/open-test.zip)

It has both one-off and abstraction subpatches, as both gop and non-gop. The non-gop has Open working, with the gop examples it's greyed out.

**Comment by agraef** [comment]
> Only problem right now, is that pdlua will send a path relative to the "Extra/pdlua" folder, instead of a full path.

Hmm, I'll have to look into that. This seems to work alright with both vanilla and purr-data, though, so I guess that whatever OS command is being called (on macOS it's open, on Linux it's gnome-open or xdg-open, on Windows it uses rundll32), is supposed to be invoked in the current canvas directory (the directory of the patch containing the object). I might be wrong about that, though, it's hard to find anything in this hall of mirrors where everything just seems to be delegated somewhere else. ;-)

In any case, I could probably adjust this behavior in pd-lua if needed. But it should be possible to do in plugdata as well, as you have the canvas directory available, otherwise you wouldn't be able to find abstractions referenced in a patch, no? Then you could just check for a relative path and chdir (or prefix the relative filename with the absolute canvas path) before executing the command.

**Comment by timothyschoen** [comment]
That would be a fine solution.

JUCE has a built-in File::startAsProcess function which will handle the opening for me, so that part won't be a problem.

**Comment by agraef** [comment]
> JUCE has a built-in File::startAsProcess function which will handle the opening for me, so that part won't be a problem.

But can it open files according to their file type? Because that's what `proc ::pd_menucommands::menu_openfile`does in vanilla. This makes sure that, e.g., a text file is opened in a text editor, an html file in a browser, etc., just as you have configured the file type associations it in your OS.

**Comment by timothyschoen** [comment]
<img width="551" alt="Screenshot 2023-01-06 at 13 51 53" src="https://user-images.githubusercontent.com/44585538/211015962-511f882a-9736-41a8-be82-ffd034b63a21.png">

Yes it can!

**Comment by agraef** [comment]
Awesome! :)

**Comment by 60-hz** [comment]
Another related interesting behaviour would be to be able to drag and drop a .pd file on Plugdata to open it as new patch.
This is very handy behaviour that I am using everyday with puredata vanilla "dnd-plugin".
Also, the plugin allows to drag and drop a .pd file on a specific patch to create the object as abstraction! Could be nice to do so from a .pd file in the PlugData browser.

**Comment by timothyschoen** [comment]
@60-hz, I agree, this is actually pretty essential imo. On macOS, you can drag a patch file onto the dock icon, but I don't think that works on Windows/Linux. I'll open an issue for this.

**Comment by timothyschoen** [comment]
The issue is already closed, you can drag and drop .pd files into plugdata now to open them.

**Comment by timothyschoen** [comment]
@agraef I see the problem now. In pdlua.c, line 576

```
path = class->c_externdir->s_name;
sprintf(pathname, "%s/%s", path, name);
```

c_externdir isn't defined for plugdata. I know you wrote some other workarounds for that, but it might be a easier solution to just set c_externdir to the "Extra/pd-lua" folder? That's less code, and you'll be certain that all problems are fixed.

**Comment by agraef** [comment]
See my comment at https://github.com/agraef/pd-lua/pull/25. The "external" there is the *Lua* object class, not the pdlua external itself. I'll look into why this doesn't have an externdir associated with it, it certainly should.

**Comment by agraef** [comment]
All done and dusted now with #339. Thanks, Tim! A big shout-out also to Alexandre who did a marvelous job updating and reorganizing the included docs, this is now also included in #339.

> The non-gop has Open working, with the gop examples it's greyed out.

This still doesn't work, though. Sorry that I keep bugging you with this, but this is such basic functionality that any seasoned Pd user will notice it immediately.

**Comment by timothyschoen** [comment]
<img width="580" alt="Screenshot 2023-01-09 at 14 15 25" src="https://user-images.githubusercontent.com/44585538/211316535-84d1d242-6a44-4e0c-9188-99d9fe3c10f9.png">

Pdlua isn't completely working over here, the hello object won't load. I get this error:

<img width="245" alt="Screenshot 2023-01-09 at 14 16 05" src="https://user-images.githubusercontent.com/44585538/211316658-8484b7ee-ec69-4623-a69d-5848540ab22c.png">

**Comment by timothyschoen** [comment]
Never mind, I forgot to re-run cmake to update the resources.

**Comment by timothyschoen** [comment]
> > The non-gop has Open working, with the gop examples it's greyed out.
> 
> This still doesn't work, though. Sorry that I keep bugging you with this, but this is such basic functionality that any seasoned Pd user will notice it immediately.

No problem! If I forget to fix a crucial problem, I encourage you to keep bugging me ;)

I think I fixed it, the problem was that GOPs pass through mouse clicks when you're clicking on empty space, similarly to pd-vanilla, but that also meant the right-click gets passed on. I've put a test in there to check if the right mouse button is down, in which case it will no longer pass through the mouse event.

**Comment by timothyschoen** [comment]
I think this can be closed now?

**Comment by agraef** [comment]
Works like a charm, thanks!
