### ISSUE TITLE
Logarithmic sliders don't initialize properly

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#436]
Consider the following patch:

```pd
#N canvas 827 239 527 327 12;
#N canvas 0 50 450 250 (subpatch) 0;
#X text 0 0 plugdatainfo <?xml version="1.0" encoding="UTF-8"?> <plugdatainfo/>;
#X coords 0 1 100 -1 1 1 1;
#X restore 0 0 graph;
#X obj 271 161 loadbang;
#X obj 331 272 vsl 17 128 1 1000 1 0 empty empty empty 0 -9 0 10 #191919 #ffffff #ffffff 0 1;
#X floatatom 326 424 11 0 0 0 - - - 12;
#X obj 203 275 vsl 17 128 0 127 0 0 empty empty empty 0 -9 0 10 #191919 #ffffff #ffffff 0 1;
#X floatatom 198 424 7 0 0 0 - - - 12;
#X msg 199 213 64, f 7;
#X msg 311 213 32, f 7;
#X obj 198 494 print a;
#X obj 326 494 print b;
#X connect 1 0 6 0;
#X connect 1 0 7 0;
#X connect 2 0 3 0;
#X connect 3 0 9 0;
#X connect 4 0 5 0;
#X connect 5 0 8 0;
#X connect 6 0 4 0;
#X connect 7 0 2 0;
```

The output in pd-vanilla is:

```
a: 64
b: 32
```

In plugdata we see:

```
a: 64
b: 32
b: 1.23906
a: 64
```

**Comment by dromer** [comment]
Not only do we see a secondary change after the initial loadbang, in particular the logarithmic sliders jump to a point that was not set by us.

**Comment by alfonso73** [comment]
Yeah, noticed the same "erratic" behavior of log sliders.
See here for a related thing
https://github.com/plugdata-team/plugdata/issues/99#issuecomment-1402674091

**Comment by alfonso73** [comment]
![image](https://user-images.githubusercontent.com/3230434/214837193-c2e5893d-a005-4375-aa4a-18c9c9413827.png)

then i close and reopen Reaper's project and...

![image](https://user-images.githubusercontent.com/3230434/214837497-08352b53-a2c8-4d9f-be55-d1a918f4f91c.png)

**Comment by alfonso73** [comment]
And btw even the linear slider gives a slightly different value after project reload.

**Comment by timothyschoen** [comment]
I think the regular init problem is solved, so this is just a problem with log sliders now

**Comment by dromer** [comment]
Yeah the issue of "double init" is resolved. Now it's just log sliders that somehow still change their state after initialization.

**Comment by tomara-x** [comment]
i don't know if those should go here or in a new issue. they're related:

https://user-images.githubusercontent.com/86204514/215276645-669ef64d-52cf-4212-8301-38c01feec706.mp4

patches: 
[lb.zip](https://github.com/plugdata-team/plugdata/files/10527651/lb.zip)

list boxes and symbol atoms will not display the messages given to them at int
list box will only display first element in the list. and as you can see it has a double init issue
bangs don't give the initial flash (might be useful in some cases and vanilla does it)

**Comment by timothyschoen** [comment]
> bangs don't give the initial flash (might be useful in some cases and vanilla does it)
> list boxes and symbol atoms will not display the messages given to them at int

Unforunately, that won't be possible, since the loadbang event will happen before the bang GUI is loaded, and after that we can never know if there was a bang or not. This is only visual of course, in the patch, the bang will still get passed on.

In the case of symbol and listbox, we should be able to init it to the right value, I'll take a look soon!

I also messed up the listbox, I was just working on that right now!

**Comment by timothyschoen** [comment]
Should be fixed!

**Comment by tomara-x** [comment]
no this one's still not. if a log slider has an initial value stored in it, it won't load the correct value when loading the patch

**Comment by timothyschoen** [comment]
I thought @dromer said it was working for him, the only problem I still see is that the reloaded values from log sliders sometimes have some rounding errors.

**Comment by tomara-x** [comment]
like this:
https://user-images.githubusercontent.com/86204514/216864630-fedda4bb-d9c2-447e-9de3-94f245502676.mp4

i don't know, sometimes it even happens in linear sliders too (depends on the number you're storing there i think)

**Comment by tomara-x** [comment]
hold your horses! that's not us! even vanilla has this!

**Comment by dromer** [comment]
@timothyschoen @tomara-x ah I wasn't even aware that there was a way to store "initial value" in a slider haha.

The issues I had was with pushing a value into a slider and that changing to some other value. That behavior at least is solved now.

If you say that plugdata behaves just like pd-vanilla than I'd say this is an upstream issue.

**Comment by tomara-x** [comment]
yeah they both behave the same in loading the files, but the fact they produce different files is a problem i think. so with all of them saved at 16
made in plugdata:
- linear loads as 16 //hooray we have that right!
- logarithmic loads as 0

made in vanilla:
- linear loads as 15.7811
- logarithmic loads as 15.5798

**Comment by tomara-x** [comment]
one more thing, we're not saving steady-on-click state in the file. so a jump-on-click saved in plugdata will have:
```
#X obj 504 208 vsl 17 128 0 127 0 0 empty empty empty 0 -9 0 10 #191919 #ffffff #ffffff 0 1; //this 1 should be 0
```
so it's always steady on click and can't be changed to jump on click. vanilla does save this correctly

**Comment by timothyschoen** [comment]
> one more thing, we're not saving steady-on-click state in the file. so a jump-on-click saved in plugdata will have:
> 
> ```
> #X obj 504 208 vsl 17 128 0 127 0 0 empty empty empty 0 -9 0 10 #191919 #ffffff #ffffff 0 1; //this 1 should be 0
> ```
> 
> so it's always steady on click and can't be changed to jump on click. vanilla does save this correctly

Also fixed!
