### ISSUE TITLE
ALSA MIDI input and/output on Linux (standalone)

### ISSUE THREAD

**Issue by agraef** [plugdata-team/plugdata#986]
There should be dedicated ALSA MIDI ports to get MIDI into and out of plugdata. I see that plugdata standalone does expose ALSA sequencer ports "from plugdata" (for capture) and "to plugdata" (for playback) which I guess are intended for this purpose. But in plugdata's MIDI settings they are listed incorrectly: "from plugdata" is listed as an input, and "to plugdata" as an output port. I'd say that this should be the other way round, i.e., plugdata should read from the "to plugdata", and write to the "from plugdata" port.

Otherwise, I don't see what the purpose of these ports should be -- create instant MIDI feedback? ;-) (Because that's in fact what happens if I enable "to plugdata" with a patch that takes, say, note input and creates any note output.) But if I leave "to plugdata" disabled in the MIDI settings then sending MIDI to that port from another application just seems to be ignored.

**Comment by agraef** [comment]
I can't even find this anywhere in the source, so it might be a JUCE issue.

**Comment by timothyschoen** [comment]
I understand the problem: I put plugdata's MIDI input under the "input" list, and outputs under "outputs", but in the settings panel, we are viewing inputs and outputs from another perspective. From an external application, "from plugdata" is an input port, but from plugdata, it's an output port. 🤦 

When you compare it to the MIDI I/O in Max, you can see what I mean:

<img width="1064" alt="Screenshot 2023-07-29 at 17 17 47" src="https://github.com/plugdata-team/plugdata/assets/44585538/52fe4b71-1b98-4ab4-96c5-1ad508f5e3ad">

**Comment by timothyschoen** [comment]
> Otherwise, I don't see what the purpose of these ports should be -- create instant MIDI feedback? ;-) (Because that's in fact what happens if I enable "to plugdata" with a patch that takes, say, note input and creates any note output.) But if I leave "to plugdata" disabled in the MIDI settings then sending MIDI to that port from another application just seems to be ignored.

That's a problem right now, I need to implement the ability to send MIDI messages to specific ports in the standalone, so that you can send and receive within the same patch without these problems. 

The purpose of these ports I guess, is to be able to interact with external MIDI app or device, regardless of whether they create a MIDI input or want to connect to an existing output. It makes it easier to send MIDI messages to pd-vanilla too, because it doesn't create any MIDI ports for itself.

**Comment by timothyschoen** [comment]
I fixed the swapped MIDI ports!

**Comment by agraef** [comment]
Well, it seems that https://github.com/plugdata-team/plugdata/commit/886c0410cffacfd778c48c7259593a6823f4d497 made things worse, now the Settings dialog doesn't work any more, it crashes plugdata. :(

That doesn't seem to be the way to do it, better revert.

**Comment by agraef** [comment]
Yes, going back to rev. https://github.com/plugdata-team/plugdata/commit/dc7b59a3cb7dd8b533b7a88e6c6617d9048a5c8e makes the Settings dialog work again, so https://github.com/plugdata-team/plugdata/commit/886c0410cffacfd778c48c7259593a6823f4d497 must be the culprit here.

**Comment by timothyschoen** [comment]
Fixed the crash with 5a68b5860e870c96dec0606e1bb8f086a94654f3

**Comment by agraef** [comment]
I can confirm that https://github.com/plugdata-team/plugdata/commit/5a68b5860e870c96dec0606e1bb8f086a94654f3 fixes the crash. But that still doesn't make the "to plugdata" port work. Even if I enable it in the MIDI settings, sending MIDI to the port does nothing. In contrast, I can enable ALSA's MIDI Through port in plugdata and send MIDI data through that without any problems. I think that there must be something wrong with the way that JUCE sets up the "to plugdata" and "from plugdata" ports, they just don't work the way that you'd expect, which makes them useless for this purpose.

**Comment by timothyschoen** [comment]
https://github.com/plugdata-team/plugdata/assets/44585538/ffd77f53-00c3-4a91-8280-cd6664e35f92

Working on a solution!

**Comment by agraef** [comment]
Well, I think that you shouldn't be allowed to write to "to plugdata" in plugdata itself, to prevent MIDI feedback. :)

I think that the JUCE system of virtual ports is a little bit confusing. The thing is, the way these virtual MIDI devices work on both Linux and Mac, the output side of "to plugdata" and the input side of "from plugdata" shouldn't actually be visible inside plugdata itself, only externally.

Anyway, after swapping the devices, the output side of "from plugdata" actually works as expected now. It's just the input side of "to plugdata" which isn't working, even if enabled as a MIDI input.

I see that "to plugdata" is created as a MIDI input in PlugDataWindow.h:396, as it should be. But I don't see that device actually being activated with MidiInput::start() anywhere, which I think it must be (that's what https://docs.juce.com/master/classMidiInput.html says). At least I don't see that call in the source. Maybe that's the only missing bit there?

**Comment by agraef** [comment]
> Well, I think that you shouldn't be allowed to write to "to plugdata" in plugdata itself, to prevent MIDI feedback. :)

What I meant there is, that you need to give the noteout popup in the video (which looks nice!) the same on-the-fly treatment as the MIDI setting dialog, treating "to plugdata" as input and "from plugdata" as output.

**Comment by agraef** [comment]
> But I don't see that device actually being activated with MidiInput::start() anywhere

Yep, that did the trick, here's the required change:

~~~diff
commit 80b7acd53ecd7bda66f4f718b993f50ffa08f457 (HEAD -> testing)
Author: Albert Graef <aggraef@gmail.com>
Date:   Sun Jul 30 19:13:39 2023 +0200

    Virtual MIDI input must be activated (fixes #986)

diff --git a/Source/Standalone/PlugDataWindow.h b/Source/Standalone/PlugDataWindow.h
index ca060a0e..b539b6f8 100644
--- a/Source/Standalone/PlugDataWindow.h
+++ b/Source/Standalone/PlugDataWindow.h
@@ -394,6 +394,7 @@ private:
 
 #if !JUCE_WINDOWS
         if (auto* newIn = MidiInput::createNewDevice("to plugdata", &player).release()) {
+            newIn->start();
             customMidiInputs.add(newIn);
         }
 #endif
~~~

**Comment by agraef** [comment]
Ok, with that sorted out, the only showstopper that keeps me from using current git is #983. I hope that you can get that sorted out soon, then I'll *really* be a happy camper. :) For the time being, I'm already having a lot of fun with v0.7.0 in Ardour!

**Comment by agraef** [comment]
I've put that up as a PR now, see #991.

**Comment by agraef** [comment]
Should be fixed on HEAD, closing.
